### PR TITLE
Parallel minetestmapper execution → a lot faster, fix geometry setting and  abort if minetestmapper isn't found to avoid spamming

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by HybridDog** [comment]
l now used it to generate a map from my testworld, its map.sqlite takes 632.2 MB. It worked although l think swap was activated. It said 272 seconds slept waiting for minetestmapper.

**Comment by est31** [comment]
Thanks for the PR, I've merged the error checking changes as fd43a4f54563dd29d15eb7bcdb3c91d5d1df53e9

About the parallelism, I'll investigate whether there is a better approach to it.

**Comment by fireglow** [comment]
Hi, the xargs -d flag only works on Linux, FreeBSD[1](https://www.freebsd.org/cgi/man.cgi?query=xargs&apropos=0&sektion=0&manpath=FreeBSD%2010.1-RELEASE%20and%20Ports&arch=default&format=html) and OpenBSD[2](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/xargs.1?query=xargs&sec=1) don't have it.
Is there a way you can make it work without -d?

**Comment by est31** [comment]
Ahh, used the NUL byte now instead the -0 param seems to be present everywhere. Thanks for pointing out.

**Comment by est31** [comment]
Fixed in 020605c420a62e47ebcb3b2343c07bf7b6034f64

**Comment by fireglow** [comment]
Cool, thanks, it's working (confirmed on FreeBSD)

**Pull request closed without merging**
